---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache package and php for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache package and php for CentOS
    package:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"  
    
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package 
    package:
      name: samba
      state: latest
    
     
    
 