- name: install mariadb package (CentOS)
  tags: mariadb,centos,db
  package:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Ubuntu)
  tags: mariadb,ubuntu,db
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"